import { Img } from "./Img";
import { Text } from "./Text";
import { OtherText } from "./OtherText";
import { Heading } from "./Heading";
import { Button } from "./Button";
import { Input } from "./Input";
import { CheckBox } from "./CheckBox";
import { RatingBar } from "./RatingBar";
import { OtherBtn } from "./OtherBtn";
import { ReactTable } from "./ReactTable";
import { OtherHeading } from "./OtherHeading";
export { Img, Text, Heading, Button, Input, OtherBtn, CheckBox, RatingBar, ReactTable, OtherText, OtherHeading };
